checks:
    method-count:
        enabled: true
        config:
            threshold: 30
    method-complexity:
        config:
            threshold: 15
    method-lines:
        config:
            threshold: 40
    argument-count:
        config:
            threshold: 5
    identical-code:
        config:
            threshold: 50
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"