checks:
    method-count:
        enabled: true
        config:
            threshold: 25
    identical-code:
        config:
            threshold: 4
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"