checks:
    method-count:
        enabled: true
        config:
            threshold: 25
    method-complexity:
      config:
        threshold: 6
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"